### ISSUE TITLE
Delegate .thumb and .url from photo to dragonfly (?)

### ISSUE THREAD

**Issue by dce** [vigetlabs/simplest_photo#1]
In order to pull in an image, I have to do something like this:

``` ruby
column(:logo) { |promo| image_tag promo.logo.image.thumb("96x96#").url } 
```

If we added `delegate :url, :thumb, to: :image` to https://github.com/vigetlabs/simplest_photo/blob/master/lib/simplest_photo/model/photo.rb, I think we could then say:

``` ruby
column(:logo) { |promo| image_tag promo.logo.thumb("96x96#").url } 
```

Makes sense to me to cut out that call to `.image`. Thoughts?

**Comment by yaychris** [comment]
I approve.
